name: 'Create TestRail testrun for PR'
description: 'This action automatically creates the structure to organize testiung on a per PR basis.'
inputs:
  testrail_token:
    description: 'Testrail API token'
    required: true
  testrail_user:
    description: 'Testrail user (ie. email account)'
    required: true
  github_token:
    description: 'Github token for the repoistory with permissions to add comments to a PR'
    required: true
  testrail_project:
    description: 'ID of the Testrail project the test run should be added to'
    required: true
  testrail_suite:
    description: 'ID of the Test Suite for the test run'
    required: true
  testrail_URL: 
    description: 'URL of the Testrail API. No trailing slash is necessary. For example "https://gs3.testrail.io"'
    required: false
    default: 'https://gs3.testrail.io'
runs:
  using: 'node12'
  main: 'dist/index.js'
