name: 'Create test run for PR'
on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  createTestRun:
    runs-on: ubuntu-latest
    steps:
      - name: Create TestRun
        uses: luzlab/testrail-createTestRun-action@main
        with:
          testrail_token: ${{ secrets.TESTRAIL_TOKEN }}
          testrail_suite: 8
          testrail_project: 1
